# Generated by Django 4.1.1 on 2022-09-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_app', '0002_rename_autor_libro_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='copia',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
